#!/usr/bin/env python
import requests, os

# Change working directory to location of this script
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

# Make request to minifier
url = 'https://cssminifier.com/raw'
data = {'input': open("../src/css/main.css", 'rb').read()}
response = requests.post(url, data=data)

print response.text
