<?php

header("Access-Control-Allow-Origin: *");

 ?>
<!DOCTYPE html><html class=no-js><meta charset=utf-8><meta content="initial-scale=1,maximum-scale=1"name=viewport><script>var stopContentUrl="http://devi.trafikanten.no/devirest.svc/json/stopid/",deviationDetailsPageUrl="https://ruter.no/avvik/avviksmelding?deviationid=",linesDepartureTimesServiceUrl="https://reiseplanlegger-ekstern.ruter.no/no/Sanntid/For/"</script><script src=//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js></script><body id=content><style>body{margin:0}#outer{padding:5px}#container{font-size:12px}#container .header,#main .loading{display:block}section.realtime .deviation{overflow:hidden}section.realtime{padding:0}section.realtime>div{background:0 0;padding:0;height:auto;overflow:hidden}section.realtime>div .time{color:#ccc}section.realtime .actionButtons,section.realtime ul li .heading .check{display:none}section.realtime>ul>li .list{overflow:hidden}section.realtime>ul>li .heading{overflow:hidden}a{color:#fff!important}.deviation>a{display:block;color:#fed100!important}.deviation>a::before{content:"⚠	";margin:0 5px 0 7.5px}#main,#outer,.travelresultsNone>p,body{background:#333!important;color:#fff;font-family:ubuntu,-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"}ul{padding-left:0;max-width:100%;margin:10px}li{border-radius:10px;border:1px solid #ccc;padding:5px;margin-bottom:10px}li:last-child{margin-bottom:0}.heading{background-color:hsla(0,0%,80%,1);color:#000;background-color:hsla(0,0%,80%,1);text-align:left;padding:2px 7.5px;font-variant:small-caps;color:hsla(0,0%,20%,1);letter-spacing:2px;font-size:1.3em;border-radius:10px 10px 0 0;margin:-5px -5px 0 -5px}.list{padding:8px;font-size:1.25em;color:#fed100}.item{margin-right:10px}.travelresultsNone{display:block!important}.clearfix{display:flex;margin:0 10px;justify-content:space-between}#realtimeUpdate,.clearfix>.time{font-size:1.2em!important;text-decoration:none;line-height:32px}#realtimeUpdate{color:#111!important;background-color:#ccc;border-radius:5px;margin:0;height:32px;min-width:100px}#realtimeUpdate.loading{color:#333!important;background-color:#bbb!important;cursor:not-allowed}#realtimeUpdate:active{background-color:#aaa}#realtimeUpdate>.left::before{content:"↻ ";font-size:1.2em;display:inline-block;font-weight:700;margin:0 5px 0 7.5px;transform:rotate(90deg)}</style><div id=outer><div id=container><div id=main><span class=loading>Laster...</span></div></div></div><script>var init=function(){},hpid=0,hpname="",loadRealtime=function(){var a=linesDepartureTimesServiceUrl;try{$("#realtimeUpdate").addClass("loading")}catch(k){console.log(k)}var d=a;if(window.location.hash){var b=window.location.hash.substring(1);if(0<b.length){b=unescape(decodeURI(b));if(-1!=b.indexOf("|"))for(var c=b.split("|"),a=a+c[0],e=1;e<c.length;e++){var g="&";1==e&&(g="?");var f=c[e],f=f.replace(" ","+"),a=a+(g+"linesToFilter="+f)}else a+=decodeURI(b);(c=b.substring(1,b.indexOf(")")))&&(hpid=c);
(b=b.substring(b.indexOf(")")+1,-1!=b.indexOf("|")?b.indexOf("|"):b.length))&&(hpname=decodeURIComponent(b))}}d==a?$("#main").html("<div class='loading'>Stoppested er ikke valgt.</div>"):($(".headerTitle").text(hpname),$("#main").load(encodeURI(a)+(0<=a.indexOf("?")?"&":"?")+"x-requested-with=XMLHttpRequest",function(b,a,c){$(document).off("click",".devLightbox2");$(".deviationIcon").unbind("click").attr("target","_new").each(function(){var a=$(this).attr("href");$(this).attr("href",a.replace("?devId=?devId=",
"?devId="));$(this).attr("href",a.replace("/no/Avvik/Avganger/",deviationDetailsPageUrl))});try{$(".actionButton.update")[0].href=location.hash}catch(h){}$(".actionButton.update").click(function(){loadRealtime();return!1});"success"!=a&&"notmodified"!=a&&$("#main").html("Feil ved lasting av sanntid.");try{$("#realtimeUpdate").removeClass("loading")}catch(h){console.log(h)}}))};function getTime(){var a=new Date;return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()}$(document).ready(function(){loadRealtime()});
var sendMessage=function(){$(document).ready(function(){var a,d;try{a=location.hash.match(/\((\d+)\)/)[1]}catch(b){console.error("Couldn't get ID of",location)}try{d=location.hash.match(/\)(.+)%/)[1]}catch(b){console.error("Couldn't get name of",location)}parent.postMessage(a+","+$("body").height()+","+d,"*");setTimeout(sendMessage,333)})};sendMessage();</script><link href=/css/ubuntu.php rel=stylesheet>
